<?php

// $order = new Mage_Sales_Model_Order();
// $orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
// $order->loadByIncrementId($orderId);

?>

<!-- <h2><?php // echo $this->__('Liquido BRL Pagamentos') 
            ?></h2>

<p>It's a demo page acting as a payment gateway interface! So don't worry you won't get charged :-)</p>

<form name="liquidobrlpaymentmethod" method="post" action="<?php // echo Mage::helper('liquidobrlpaymentmethod')->getPaymentGatewayUrl(); 
                                                            ?>">
    <input type="hidden" name="orderId" value="<?php // echo $orderId; 
                                                ?>">
    <input type="submit" value="<?php // echo $this->__('Make Payment') 
                                ?>" />
</form> -->

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('liquidobrlpaymentmethod/css/index.css'); ?>">
<div class="liquido-container">
    <h1><?php echo $this->__('Liquido BRL Pagamentos') ?></h1>
    <h2>Escolha como quer pagar</h2>
    <?php
    $brazil_payin_methods = Mage::helper('liquidobrlpaymentmethod')->getLiquidoBrazilPayInMethods();
    ?>

    <ul id="payin-methods">
        <?php foreach ($brazil_payin_methods as $payin_method) : ?>
            <a class="payin-method-link-brl" href="<?php echo Mage::helper('liquidobrlpaymentmethod')->getPayInMethodViewRoute($payin_method["title"]) ?>">
                <li>
                    <img src="<?php echo $this->getSkinUrl($payin_method["image"]); ?>" alt="PayIn method image">
                    <div class="payin-method-single">
                        <p><?php echo $payin_method["title"]; ?></p>
                        <small><?php echo $payin_method["description"]; ?></small>
                    </div>
                </li>
            </a>
        <?php endforeach; ?>
    </ul>
</div>